name: flutter_reference

packages:
  - apps/**
  - packages/**

scripts:
  analyze:
    name: Analyze
    description: Runs flutter analyze on all packages.
    run: flutter analyze .
    exec:
      concurrency: 1
  format:
    name: Format
    description: Runs flutter format on all packages.
    run: dart format --set-exit-if-changed .
    exec:
      concurrency: 1

  test:
    name: Test
    description: Runs flutter test on all packages.
    run: bash $(git rev-parse --show-toplevel)/scripts/test_and_report.sh .
    exec:
      concurrency: 1
  generate-all:
    name: Generate
    description: Runs build_runner on all packages.
    run: |
      grep -q "build_runner" pubspec.yaml && dart run build_runner build --delete-conflicting-outputs || echo "Skipping build_runner in $MELOS_PACKAGE_NAME"
    exec:
      concurrency: 1
  clean-all:
    name: Clean
    description: Runs flutter clean on all packages.
    run: flutter clean
    exec:
      concurrency: 1
  get-all:
    name: Get
    description: Runs flutter pub get on all packages.
    run: flutter pub get
    exec:
      concurrency: 1
  rebuild-all:
    name: Rebuild all the projects
    description: It runs a flutter clean on all packages and gets the depenendencies
    run: |
      set -e
      melos run clean-all
      melos run get-all
      melos run generate-all
  start:
    name: Start the app
    run: |
      cd apps/reference
      if ! xcrun simctl list | grep -q "Booted"; then
        echo "No iOS Simulator is running. Starting one..."
        open -a Simulator
        sleep 30
      fi
      flutter run --debug --flavor development --dart-define=FLAVOR=dev
  upgrade-all:
    name: Update all the projects
    description: It runs a flutter pub upgrade on all packages and gets the depenendencies
    run: flutter pub upgrade
    exec:
      concurrency: 1
