name: reference
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0

environment:
  sdk: ^3.6.1

dependencies:
  categories:
    path: ../../packages/categories
  core:
    path: ../../packages/core
  cupertino_icons: ^1.0.8
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  go_router: ^14.8.0
  network:
    path: ../../packages/network
  previously_searched:
    path: ../../packages/previously_searched
  search_recommendation:
    path: ../../packages/search_recommendation
  search_suggestion:
    path: ../../packages/search_suggestion
  ui_components:
    path: ../../packages/ui_components
  very_good_analysis: ^7.0.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  get_it: ^8.0.3
  mockito: ^5.0.0
  mocktail: ^1.0.4
  remove_from_coverage: ^2.0.0

flutter:
  uses-material-design: true
