name: network
description: "A network package project."
version: 0.0.1
homepage:
publish_to: "none"

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../core
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  get_it: ^8.0.3

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_flutter: ^1.1.0
  mocktail: ^1.0.4
  remove_from_coverage: ^2.0.0
  very_good_analysis: ^7.0.0
