include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    avoid_final_parameters: false
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_if_elements_to_conditional_expressions: false
    lines_longer_than_80_chars: false
    document_ignores: false
    unnecessary_lambdas: false

analyzer:
  exclude:
    - test/**/mock_*.dart
    - test/**/mocks/*.dart
    - lib/**.g.dart
