name: cmp_categories
description: "Categoires package project."
version: 0.0.1

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  cmp_widgets:
    path: ../../packages/cmp_widgets

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  bloc_test: ^10.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/categories.json
    - assets/images/categories/
