name: core
description: "A core package project."
version: 0.0.1
homepage:
publish_to: "none"

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  remove_from_coverage: ^2.0.0
  very_good_analysis: ^7.0.0
