name: Analyze

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  analyze:
    name: Run flutter analyze
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Run analyze on all packages
        run: |
          ls $HOME/.pub-cache/bin/
          $HOME/.pub-cache/bin/melos analyze
