name: Analyze Workflow
on:
  push:
    branches:
      - "**"

jobs:
  analyze:
    name: Run flutter analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"
          cache: true

      - name: Setup melos
        uses: bluefireteam/melos-action@v3

      - name: Run analyze on all packages
        run: |
          melos analyze
