name: Reusable Setup

on:
  workflow_call:
    outputs:
      packages:
        description: "List of found packages"
        value: ${{ jobs.setup.outputs.found_packages }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      found_packages: ${{ steps.list-packages.outputs.packages }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"
          cache: true

      - name: Find All Packages
        id: list-packages
        run: |
          PACKAGES=$(find . -name 'pubspec.yaml' -exec dirname {} \; | tr '\n' ' ')
          echo "packages=$PACKAGES" >> $GITHUB_OUTPUT

      - name: Install Dependencies
        run: |
          for package in ${{ steps.list-packages.outputs.packages }}; do
            echo "Installing dependencies in $package"
            cd $package
            flutter pub get
            cd -
          done
