name: Test Workflow

on:
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  test:
    name: Run flutter test
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"
          cache: true

      - name: Setup melos
        uses: bluefireteam/melos-action@v3

      - name: Run test on all packages
        run: |
          melos test
